;===========================================================================
; 工具启动命令配置文件
; 版本：V2.0.1
; 作者：Super403
;
; 配置格式说明：
; [工具名称]             ; 必须与工具目录名称完全一致
; type = powershell      ; 可选，指定使用powershell运行命令，如果不指定则使用cmd
; command = 要执行的命令  ; 必选，指定要执行的具体命令
;
; 如果工具名称未在此配置文件中指定，将默认打开一个标题为工具名的cmd窗口
;
; 示例配置：
; [示例工具1]
; type = powershell
; command = python -m http.server 8080
;===========================================================================

[示例工具]
command = start C:\WINDOWS\system32\calc.exe

[Fscan]
command = fscan.exe -hf ../../GUI/target/ip.txt -o ../../GUI/output/fscan.txt

[TscanPlus]
command = TscanPlus.exe





















































